import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Homeview from '@/components/Homeview'
import Header from '@/components/Header'
import Aboutus from '@/components/Aboutus'
import Ouroffer from '@/components/Ouroffer'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Agencja Pośrednictwa Pracy - Work Station</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative'>
        <Header />
        <Homeview />
        <Aboutus />
        {/* <Ouroffer /> */}
        <Contact />
      </main>
    </>
  )
}
